credentials:
  usernames:
    admin:  # 您的帳號名稱
      email: cksxxb123@gmail.com  # 您的電子郵件
      name: admin  # 您的顯示名稱
      password: e94021107  # 密碼：admin123
    user1:
      email: cksxxb123@gmail.com
      name: yuan
      password: e94021107
cookie:
  expiry_days: 60
  key: 'your_secret_key'  # 可以是任何隨機字串
  name: streamlit_auth
preauthorized:
  emails:
    - admin@example.com 