credentials:
  usernames:
    admin:  # 您的帳號名稱
      email: cksxxb123@gmail.com  # 您的電子郵件
      name: admin  # 您的顯示名稱
      password: $2b$12$T1BkDDqF0RiD7CeJa7/Y8.IPWB5c5Zm3qoVhYoKJFfEJ3IxHBPEi.  # 密碼：admin123
    user1:
      email: cksxxb123@gmail.com
      name: yuan
      password: $2b$12$T1BkDDqF0RiD7CeJa7/Y8.IPWB5c5Zm3qoVhYoKJFfEJ3IxHBPEi.  # e94021107
cookie:
  expiry_days: 60
  key: 'your_secret_key'  # 可以是任何隨機字串
  name: streamlit_auth
preauthorized:
  emails:
    - cksxxb123@gmail.com 