version: "3.8"
services:
  finance-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-e94021107}
      - USER_PASSWORD=${USER_PASSWORD:-e94021107}